"""Write static/js/label_videos.js (the grid's clip list and button tooltips) and
static/videos/manifest.json (provenance per clip) from tools/stamps.json and
the render logs. Fails if a selected clip is missing, over 3 MB, or was not
checked against its label.

usage: python build_video_manifest.py [--allow-missing]   (preview while rendering)
"""
import glob
import sys
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
VID = os.path.join(SITE, "static", "videos")
PLATFORM = {"robomimic": "robomimic", "mimicgen": "MimicGen", "robocasa": "RoboCasa"}
MAX_BYTES = 3 * 1024 * 1024
TOL = 1e-6            # |lambda_rendered - lambda_label| counted as reproduced

renders = {}
for p in sorted(glob.glob(os.path.join(HERE, "render_log", "render_*.jsonl"))):
    for line in open(p):
        r = json.loads(line)
        if "error" not in r:
            renders[r["file"]] = r          # last successful render wins

tasks, manifest, problems = [], [], []
for s in json.load(open(os.path.join(HERE, "stamps.json"))):
    clips = []
    n_st = s["n_by_class"]["stable"]
    for c in s["clips"]:
        if not c["available"]:
            if n_st == 0:
                tip = (f"No stable stamp: none of the {s['n_stamps']:,} {s['task']} "
                       f"demonstration stamps is labeled stable at m = 2.0")
            else:
                tip = (f"Only {n_st} {s['task']} demonstration stamp"
                       f"{'s are' if n_st > 1 else ' is'} labeled stable at m = 2.0")
            clips.append({"file": None, "cls": c["class"], "tip": tip})
            manifest.append({"task": s["task"], "platform": s["platform"],
                             "button": c["button"], "class": c["class"],
                             "file": None, "reason": tip})
            continue
        f = c["file"]
        path = os.path.join(VID, f)
        r = renders.get(f)
        if r is None or not os.path.exists(path):
            problems.append(f"missing render: {f}")
            if "--allow-missing" in sys.argv:
                clips.append({"file": None, "cls": c["class"], "tip": "not rendered yet"})
            continue
        size = os.path.getsize(path)
        if size > MAX_BYTES:
            problems.append(f"{f} is {size / 1e6:.2f} MB (> 3 MB)")
        ok = r["abs_diff"] <= TOL
        tip = (f"{c['class'].upper()} · λ̄ = {c['lambda_bar']:+.3f} "
               f"(SE {c['lambda_se']:.3f}) · demo {c['demo_id']}, t = {c['t']}")
        if not ok:
            tip += (f" · note: rendered branches give λ̄ = "
                    f"{r['lambda_rendered']:+.3f}")
        if c["class"] == "stable" and n_st == 1:
            tip += " · the only stable stamp for this task"
        clips.append({"file": f, "cls": c["class"], "tip": tip})
        manifest.append({
            "task": s["task"], "platform": s["platform"], "button": c["button"],
            "class": c["class"], "file": f, "demo_id": c["demo_id"], "t": c["t"],
            "lambda_bar_label": c["lambda_bar"], "lambda_se_label": c["lambda_se"],
            "lambda_bar_rendered": r["lambda_rendered"], "abs_diff": r["abs_diff"],
            "reproduced": ok, "camera": r["camera"], "replay_history": r.get("history"),
            "K": s["K"], "N": s["N"],
            "sigma_u": s["sigma_u"], "gate": s["gate"], "frames": r.get("n_frames"),
            "fps": 20, "size": [640, 480], "bytes": size,
            "labels_file": os.path.relpath(s["labels_table_file"], os.path.dirname(SITE)),
            "labels_run_file": os.path.relpath(s["labels_run_file"], os.path.dirname(SITE))})
    tasks.append({"platform": s["platform"], "platformLabel": PLATFORM[s["platform"]],
                  "task": s["task"], "clips": clips})

if problems and "--allow-missing" not in sys.argv:
    raise SystemExit("\n".join(problems))
if problems:
    print("\n".join(problems))
with open(os.path.join(SITE, "static", "js", "label_videos.js"), "w") as fo:
    fo.write("// Generated by tools/build_video_manifest.py -- do not edit by hand.\n")
    fo.write("var LABEL_VIDEO_TASKS = " + json.dumps(tasks, indent=1, ensure_ascii=False) + ";\n")
with open(os.path.join(VID, "manifest.json"), "w") as fo:
    json.dump(manifest, fo, indent=1, ensure_ascii=False)
n = sum(1 for m in manifest if m["file"])
bad = [m["file"] for m in manifest if m["file"] and not m["reproduced"]]
print(f"{n} clips, {len(manifest) - n} unavailable slots, "
      f"{len(bad)} not reproducing their label{': ' + ', '.join(bad) if bad else ''}")
